#!/bin/bash

controlDir=$1 # Контролируемая директория
backup="/home/user/lab6/backup" # Каталог резервных копий
controlSum="/home/user/lab6/ControlSum"
eventlog="/home/user/lab6/eventlog" 

# Если существует директория с эталонными копиями, удаляем её
if [ -d "$backup" ]; then
    rm -r "$backup"
fi
# Создаем директорию для хранения эталонных копий
mkdir -p "$backup"

# Копируем содержимое мониторимой директории в директорию с эталонами
cp "$controlDir"/* "$backup"

# Если существует файл с контрольными суммами, удаляем его
if [ -e "$controlSum" ]; then
    rm "$controlSum"
fi

# Создаем новый файл для хранения контрольных сумм
touch "$controlSum"

# Для каждого файла в директории с эталонами считаем контрольную сумму и записываем в файл
for f in "$backup"/*; do
    sha512sum "$f" >> "$controlSum"
done

# Если существует файл журнала событий, удаляем его
if [ -e "$eventlog" ]; then
    rm "$eventlog"
fi

# Создаем новый файл журнала событий
touch "$eventlog"

# Check the given file to see if they exist in backup directory.
# If so, check the sha1sum value of given file to see if they have been changed.
# If the file has been changed, recover it from backup folder using cp comand.
# Using date command for outputing current time.
# Using logger command for output log into system event viewer.
checksum() {
    filename=$1
    if [[ ! -f "${backup}/${filename}" ]]
    then
        return 0
    fi
    expected=$(sha256sum "${backup}/${filename}" | awk '{print $1}')
    actual=$(sha256sum "${controlDir}/${filename}" | awk '{print $1}')
    if [ ${actual} != ${expected} ]
    then
        cp -f "${backup}/${filename}" "${controlDir}/${filename}"
        logstr="$date '+%Y-%m-%d %H:%M:%S': The file [${controlDir}/${filename}] was changed (checksum didn't match), has been recovered from the backup [${backup}/${filename}]"
        echo "$logstr" >> "$eventlog"
    fi
}

# List all files inside controlDir folder and call checksum function.
main() {
    for item in "${controlDir}"/*; do
        if [[ -f "${item}" ]]
        then
            filename=$(basename "${item}")
            checksum "${filename}"
        fi
    done
}

# Call main function for checking each 5 seconds.
while :; do
    main "${controlDir}"
    sleep 5
done
